### ISSUE TITLE
Are R "data objects" accessible in Stata with Rcall?

### ISSUE THREAD

**Issue by aalexandersson** [haghish/MarkDoc#10]
Which R objects are accessible in Stata? It seems that "data objects" are not accessible in Stata with Rcall. I use R 3.3.0 and Stata 14.

According to http://www.haghish.com/packages/Rcall.php, "most" of the R objects are accessible in Stata. But I am unable to access "data objects" in the the "RecordLinkage" package. The package has two functions, compare.dedup for deduplication of a single dataset and compare.linkage for linking two datasets together. Both functions return an object of class "RecLinkData which includes, among other components, the resulting comparison patterns as component pairs. In the article R Journal Vol 2/2, December 2010 (available at https://journal.r-project.org/archive/2010-2/RJournal_2010-2_Sariyar+Borg.pdf), such an object was referred to as a data object. 

I use the compare.linkage function in R despite that I prefer Stata because the package is better for record linkage than everything available in Stata.  But for ease of troubleshooting, I will demonstrate the problem with the function compare.dedup. The following five lines of code are taken directly from the R Journal article on pages 61-62 :

R: library(RecordLinkage)
R: data(RLdata500)
R: RLdata500[1:5, ]
R: rpairs <- compare.dedup(RLdata500, identity = identity.RLdata500)
R: rpairs$pairs[1:5, ]

The last command should have created five lines of output but it did not. I can reproduce the results both directly in R and from within Stata using Roger Newson's command rsource but not using Rcall. 

Anders

**Comment by haghish** [comment]
please __read the Rcall manual__ carefully. The reason is that the __$__ sign is preserved for Stata Globals and if you want to use it in [Rcall](www.haghish.com/packages/Rcall.php) you should put a backslash behind it. i.e.

     R: rpairs\$pairs[1:5, ]

Also, __Rcall__ can in theory return all R classes to Stata. At the moment, -- as noted in the help file -- it returns __character__, __numeric__, __matrix__, and __list__ classes, and it has a function for returning __dataframe__. You should figure out to pass other classes by converting them to any of the available classes or update the program! ;)

**Comment by haghish** [comment]
BTW, this issue had nothing to do with __MarkDoc__ package ;)

**Comment by aalexandersson** [comment]
Sorry, it has been a long week. The backslash fixed the issue I had with
Rcall.

**Comment by haghish** [comment]
Glad to hear that
