### ISSUE TITLE
Including an image with dynamic path

### ISSUE THREAD

**Issue by louisdecharson** [haghish/MarkDoc#12]
Hi, 
I want to include image which has a dynamic path (the image is created in a loop) but the markdoc output stopped when I do so. 
My code looks like:
```
foreach var in $mylist {
   box `var'
   graph export ./figs/fig_`var'.eps, replace
   txt ![Boxplot of variable `var'](./figs/fig_`var'.eps)
}
```
The code is running fine although the `.docx` generated by Markdoc stopped after `graph export` in the first iteration.
The log file `.smcl` looks fine, title and path to the file are correct : ``var'` is correctly replaced by the name of the var. 
Is it normal behaviour ? Is there any workaround ?
Thanks a lot for your time.
Louis

**Comment by haghish** [comment]
PostScript is naturally not supported!

**Comment by haghish** [comment]
Alternatively, read the `img` command.

**Comment by louisdecharson** [comment]
I do not understand your answer. PostScript *is* working. 
All the other images without a dynamic path are rendered perfectly. 
See the example below: 
```
capture log close
qui log using test_markdoc, replace smcl
sysuse auto.dta
graph box price
graph export box_price.eps, replace
/***
![Box of price](box_price.eps)
***/
qui log c
markdoc test_markdoc, replace export(docx) install 
```
This code is producing the attached output:
<img width="1276" alt="screen shot 2016-09-28 at 23 12 19" src="https://cloud.githubusercontent.com/assets/3234544/18932554/426e7ed2-85d1-11e6-95d6-1076aa6017db.png">

The reason I prefer not using `img` command is that it's not working with Unix-console (I'm using Stata inside emacs). Doing it leads to the error `translator Graph2png not found`.

The problem is really with the dynamic path. Again, all the other .eps graphs are rendered perfectly.

**Comment by haghish** [comment]
Ok, PostScript can be rendered in LaTeX and Docx. But not if you create HTML for example. So I understand the problem better now. Yes, unfortunately, in Unix console you can't export PNG or if you run batch mode. 

Still, there should be no problem with the dynamic path. I will need more information before I can help. 

Also, I think this is a kind of question that should be discussed on [statalist](http://www.statalist.org/) because others might have similar questions or ideas to solve it. Please post the question with detailed description there and provide the following:

- a do-file to reproduce the error
- the smcl log-file
- complete description of your OS, Stata version, and package version

I'll take it from there

**Comment by louisdecharson** [comment]
Thanks a lot for your answer. You're right, I'm going to use Statalist, here is the [post](http://www.statalist.org/forums/forum/general-stata-discussion/general/1358453-dynamic-path-on-markdoc)
